[build]
  publish = "/"
  command = "# no build command"

[[redirects]]
  from = "/*"
  to = "/HTML/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Enable Netlify Identity for authentication
[template.environment]
  NETLIFY_IDENTITY = "enabled"

# Enable Functions for server-like functionality
[functions]
  directory = "functions"
  node_bundler = "esbuild"

# Headers to enable security and cache control
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=3600"
    
[[headers]]
  for = "/*.js"
    [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.css"
    [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/images/*"
    [headers.values]
    Cache-Control = "public, max-age=604800" 